Cql4bonnie 1002
MeasureAuthoringTool/bonnie_bundler pull request #105
Opened 2017-08-31 00:41 UTC by edeyoung

This PR includes several changes from James' cql4bonnie_code_review branch (although not all of the changes so that it would merge nicely in with the latest code).

2017-08-31 12:35 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +        #hqmf_entry = file.glob(File.join('**','**.xml')).select {|x| x.name.match(/.*eMeasure.xml/) && !x.name.starts_with?('__MACOSX') }.first
Should this line be removed?

2017-08-31 12:43 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +      hqmf_model.backfill_patient_characteristics_with_codes(HQMF2JS::Generator::CodesToJson.from_value_sets(value_set_models))
Should this line still be: hqmf_model.backfill_patient_characteristics_with_codes(all_codes_and_code_names)?

2017-08-31 15:52 UTC, holmesie requested changes

2017-08-31 15:52 UTC, holmesie commented on Gemfile
> +gem 'nokogiri', '~> 1.6.8'
This version of nokogiri contains several vulnerabilities in libxml2 and libxslt (see: https://github.com/sparklemotion/nokogiri/issues/1615). We should try using 1.7.2 instead, which is what bonnie master is at now.

2017-08-31 15:52 UTC, holmesie commented on lib/measures/loading/qdm_loader.rb
> +          elsif xml_file_paths[:SIMPLE_XML]
Do we still care about dealing with SimpleXML? I don't think we need to anymore.

2017-08-31 16:36 UTC, edeyoung commented on lib/measures/loading/qdm_loader.rb
> +          elsif xml_file_paths[:SIMPLE_XML]
we should really just get rid of QDM loading entirely, but I don't think that's in the scope of this particular PR. Since this is for the QDM-based measures which still have SimpleXML, I'd like to leave it for now because of potential cascading changes removing it would involve (removing the :SIMPLE_XML key, things that reference this elsewhere in the code, etc.)

2017-08-31 16:47 UTC, edeyoung commented on Gemfile
> +gem 'nokogiri', '~> 1.6.8'
is this something that should wait until the big security update? it won't let me update bonnie_bundler to 1.7.2 because HDS is on 1.6.8.

2017-08-31 16:49 UTC, holmesie commented on Gemfile
> +gem 'nokogiri', '~> 1.6.8'
In that case we would have to wait. Lets remember that this is here though, and make it part of that update.

2017-08-31 16:49 UTC, holmesie approved these changes
Feedback addressed

2017-08-31 18:14 UTC, hossenlopp commented on Gemfile
> +gem 'nokogiri', '~> 1.6.8'
I already have this updated in the work in progress branch. https://github.com/projecttacoma/bonnie_bundler/tree/cql4bonnie_gems_updates

2017-09-01 15:06 UTC, c-monkey approved these changes
changes look good.
bonnie unit tests pass
bonnie_bundler unit tests pass

2017-09-01 19:27 UTC, merged

2017-09-01 19:34 UTC, edeyoung commented
For some reason travis started failing the tests. Confirmed this is a travis issue after checking a commit that previously worked (ed0cac9), which failed on another run.

![](https://files.slack.com/files-pri/T0300BTQY-F6WHUCH7S/pasted_image_at_2017_09_01_03_01_pm.png)

2017-09-01 19:35 UTC, edeyoung commented
![image](https://user-images.githubusercontent.com/11574199/29985006-20d35d4c-8f2b-11e7-8f0a-368da15d4862.png)