BONNIE-1085 Fix the way that valuesets are loaded so that, if include…
MeasureAuthoringTool/bonnie_bundler pull request #111
Opened 2017-09-21 17:10 UTC by alexanderelliott121

Updates value upload logic such that if draft is selected, it will use draft instead of version.

JIRA at: https://jira.mitre.org/browse/BONNIE-1085
Test at: https://jira.mitre.org/browse/BONNIE-1101

2017-09-21 18:07 UTC, holmesie submitted a review, later dismissed
JIRA test passes; Local tests pass; Code looks good; Approved

2017-09-22 15:31 UTC, jbradl11 commented
Code makes sense and the Jira Test passes, however, is there a way to write a unit test for this? Isn't this a fix for a bug we found in production? If so, we should try to write a new unit test that will cover this situation.

2017-09-22 16:42 UTC, edeyoung commented
On hold pending discussion with super testers on Monday 9/25

2017-09-25 20:25 UTC, edeyoung commented
Discussions with super testers: 

Including "draft" should always get you the latest version of the value sets (the default profile in Bonnie) regardless of what is in the measure.

2017-09-25 20:26 UTC, edeyoung commented on lib/measures/loading/value_set_loader.rb
> +                vs_data = api.get_valueset(value_set[:oid], include_draft: includeDraft, profile: profile)
from discussions with MDs, it appears when draft is selected, we should always retrieve the latest value set. In that case, we would want to always use the default profile when draft is selected.

2017-09-25 23:26 UTC, edeyoung submitted a review, later dismissed
See notes regarding discussion with MDs

2017-09-26 14:34 UTC, alexanderelliott121 commented
JIRA test update to reflect functional chagnes.

2017-09-26 16:00 UTC, jbradl11 requested changes
JIra Test screen shots seem to be wrong for this PR. Please update them.

2017-09-27 12:17 UTC, alexanderelliott121 commented
JB identified a bug: if you run through the jira test twice, it stops working.  I've got a fix, but the cause of this raises an issue that I'd like to clear up with Lizzie before I push it.

2017-10-02 16:30 UTC, lukoktonos submitted a review, later dismissed
Code looks good--JIRA and regression tests pass.  I agree with @jbradl11 about unit tests, so will approve with the understanding that either unit tests will be added as per his comment, or the justifications for having only a JIRA tests make sense when they are provided.

2017-10-02 20:09 UTC, jbradl11 commented
@alexanderelliott121 Please add unit tests to this PR.

2017-10-02 20:14 UTC, lukoktonos requested changes
I agree that unit tests are needed for this PR.

2017-10-03 17:46 UTC, alexanderelliott121 commented
Unit tests added

2017-10-03 18:11 UTC, lukoktonos requested changes
Tests seem to cover the changes and pass--some cleanup requested--see comments.

2017-10-03 18:11 UTC, losborne commented on test/unit/value_set_loading_test.rb
> +
There's some trailing whitespace here.

2017-10-03 18:11 UTC, losborne commented on test/unit/value_set_loading_test.rb
> +  test "Loading with IncludeDraft and no Profile or Version" do
Rubocop is saying it prefers single quotes throughout this file as per ruby convention--I would change them since the requires at the top use single quotes.

2017-10-03 18:11 UTC, losborne commented on test/unit/value_set_loading_test.rb
> +
Adding some style-related comments based on rubocop analysis--I think it would be fairly quick to change a few things and have it pass the linter, and it would make the file a bit cleaner.

Here it suggests adding a comment to explain what the class/test is for

2017-10-03 18:11 UTC, losborne commented on test/unit/value_set_loading_test.rb
> +    #Expects that draft and default profile will be used
Misisng space after the '#', here and below

2017-10-03 18:11 UTC, losborne commented on test/unit/value_set_loading_test.rb
> +
Some trailing whitespace here as well.

2017-10-03 18:11 UTC, losborne commented on test/unit/value_set_loading_test.rb
> +
Delete this empty line at the end of the block

2017-10-03 18:11 UTC, losborne commented on test/unit/value_set_loading_test.rb
> +
Delete one of these blank lines.

2017-10-03 18:11 UTC, losborne commented on test/unit/value_set_loading_test.rb
> +end
Add a new line at the end.

2017-10-04 13:17 UTC, lukoktonos approved these changes
Changes look good. Approved

2017-10-04 15:59 UTC, jbradl11 approved these changes
Tests pass. Jira test passes. Looks good.

2017-10-05 12:26 UTC, edeyoung commented on lib/measures/loading/value_set_loader.rb
>            set = HealthDataStandards::SVS::ValueSet.where({user_id: user.id, oid: value_set[:oid], version: query_version}).first() unless use_cache
if we have "include draft" should we always query for the latest? In that case, should we never check the db for existing if we have "include draft"?

2017-10-05 12:35 UTC, edeyoung commented on lib/measures/loading/value_set_loader.rb
>            set = HealthDataStandards::SVS::ValueSet.where({user_id: user.id, oid: value_set[:oid], version: query_version}).first() unless use_cache
This would address BONNIE-1080

2017-10-05 13:27 UTC, alexanderelliott121 commented on lib/measures/loading/value_set_loader.rb
>            set = HealthDataStandards::SVS::ValueSet.where({user_id: user.id, oid: value_set[:oid], version: query_version}).first() unless use_cache
You actually do need to check the db, since if there is a draft vs for that measure, you need clear it out before getting the new one.

2017-10-05 17:18 UTC, edeyoung commented on lib/measures/loading/value_set_loader.rb
>            set = HealthDataStandards::SVS::ValueSet.where({user_id: user.id, oid: value_set[:oid], version: query_version}).first() unless use_cache
I see that my comment has been addressed by line 159. thanks!

2017-10-05 17:19 UTC, edeyoung commented
travis failures are unrelated to this PR and are being addressed separately.

2017-10-05 17:20 UTC, merged