Cql4bonnie remove qdm
MeasureAuthoringTool/bonnie_bundler pull request #113
Opened 2017-10-04 12:25 UTC by mayerm94

Pull requests into Bonnie Bundler require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-10-04 12:32 UTC, mayerm94 commented
Bonnie_bundler had failing tests because of an error in a backend HQMF execution engine that was only used by the bundle feature. That error spawned from an upgrade in mongodb from 2.* to > 3.0. Since we do not use bundles with CQL, it is safe to remove the functionality and the tests that have been causing failed travis builds. This PR removes the bundle feature and HQMF loading. Should be tested along side https://github.com/projecttacoma/bonnie/pull/860

https://jira.mitre.org/browse/BONNIE-1117

2017-10-05 18:12 UTC, jbradl11 commented on lib/measures/loading/mat_loader.rb
> -      Measures::CqlLoader.mat_cql_export?(zip_file) || Measures::QDMLoader.mat_hqmf_export?(zip_file)
This file was used as an abstraction layer for uploading QDM and CQL based measures. Now that we are not supporting QDM+HQMF measures, this file could be removed and we could just use the CqlLoader class. This may be outside of the scope of this PR.

2017-10-09 13:00 UTC, alexanderelliott121 requested changes

2017-10-09 13:00 UTC, alexanderelliott121 commented on lib/measures/loading/value_set_loader.rb
> -    def self.load_value_sets_from_xls(value_set_path)
This still looks like it is in use in one rake task
Parser_comparison.rake

2017-10-09 13:00 UTC, alexanderelliott121 commented on lib/measures/loading/sources_loader.rb
> -  class SourcesLoader
Used 
bonnie/lib/tasks/dashboard.rake
and 
bonnie/lib/tasks/sources.rake

2017-10-09 13:00 UTC, alexanderelliott121 commented on lib/measures/loading/value_set_loader.rb
> -      parser = HQMF::ValueSet::Parser.new()
Also used in bonnie rake task

2017-10-09 13:00 UTC, alexanderelliott121 commented on lib/measures/loading/value_set_loader.rb
> -      parser = HQMF::BlackList::Parser.new()
Used in bonnie rake task

2017-10-12 16:45 UTC, jbradl11 commented on lib/models/cql_measure.rb
> +    HQMF::Measure::LogicExtractor.get_measure_logic_diff(self,other,true)
I don't think LogicExtractor will work as is with CQL measures. Has this been tested?

2017-10-12 20:08 UTC, jbradl11 commented on test/unit/measure_complexity_test.rb
> -  test "calculate complexity" do
I believe we still calculate complexity on CQL measures. I think we should have a test for it. Might be out of scope for this PR?

2017-10-16 16:59 UTC, alexanderelliott121 approved these changes
Referring rake tasks cleaned up

2017-10-16 17:04 UTC, jbradl11 commented on test/unit/load_measure_logic_test.rb
> -  test "Loading a MAT export zip file" do
Do we have something similar to this for CQL measures?

2017-10-16 19:11 UTC, mayerm94 commented on test/unit/load_measure_logic_test.rb
> -  test "Loading a MAT export zip file" do
test/unit/measure_diff_test.rb

2017-10-16 19:25 UTC, jbradl11 submitted a review, later dismissed

2017-10-17 15:29 UTC, merged