BONNIE-1154 Fixes whitespace issue.
MeasureAuthoringTool/bonnie_bundler pull request #124
Opened 2017-11-14 16:10 UTC by alexanderelliott121

Pull request changes the way the elm is parsed to make it resemble the human readable.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1154
- [X] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Code coverage has not gone down and all code touched or added is covered.
    * In rare situations, this may not be possible or applicable to a PR. In those situations:
        1. Note why this could not be done or is not applicable here:
        2. Add TODOs in the code noting that it requires a test
        3. Add a JIRA task to add the test and link it here:
- [X] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: https://jira.mitre.org/browse/BONNIE-1177
- [X] Justification for using JIRA tests: Pure gui change, difficult to unit test.
- [X] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-11-16 17:58 UTC, c-monkey approved these changes
minor feedback, I don't care if we fix it, it's just a style suggestion, nothing functional

2 spaces matches human readable well

2017-11-16 17:58 UTC, c-monkey commented on lib/measures/elm_parser.rb
> +          if (/^define/ =~ child.to_html)
the ruby style guide suggests parenthesis around conditionals is inappropriate and it doesn't match the style of the rest of this file

2017-11-17 15:23 UTC, lukoktonos requested changes
The JIRA test's image currently matches the `cql4bonnie` behavior for me:
![image](https://user-images.githubusercontent.com/14879344/32954480-38deecde-cb81-11e7-9109-0cdcd933d95c.png)

This is what it looks like for me on this branch:
![image](https://user-images.githubusercontent.com/14879344/32954498-44d9a8a8-cb81-11e7-8af6-e57b3c9f1816.png)

I believe the latter is correct and the JIRA test just needs to be updated.

2017-11-20 13:38 UTC, edeyoung commented
This is what i see in the jira test:

![image](https://user-images.githubusercontent.com/11574199/33020952-1e4c3e72-cdce-11e7-909c-e714c1842c43.png)


It looks like your latter image. Maybe the test got updated since you last checked? Can you take another look, @losborne?

2017-11-20 14:40 UTC, losborne commented
@edeyoung When I am on the branch `BONNIE-1154_WhitespaceFix`, it looks like this:
![image](https://user-images.githubusercontent.com/14879344/33023633-c6999446-cdd6-11e7-8ae9-b726cd333c06.png)

The JIRA test says it should look like this when on that branch:
![image](https://user-images.githubusercontent.com/14879344/33023648-d3811116-cdd6-11e7-9449-88c38517b391.png)

2017-11-20 15:07 UTC, lukoktonos approved these changes
Looks good.  JIRA Test screenshot updated.

2017-11-21 13:07 UTC, merged