Add unreferenced support libraries to cql_dependency_structure.
MeasureAuthoringTool/bonnie_bundler pull request #136
Opened 2018-03-20 18:53 UTC by jbradl11

Pull requests into Bonnie Bundler require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

A measure will fail to load properly if a measure has a support library, but does not use any of the definitions or functions in that library and instead only references a value set or a DRC from the library. This issue is due how we build cql_dependency_structure. In order to fix this, we now add all libraries to the cql_dependency_structure. If the library has no dependencies we assign it to an empty hash. 

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1270
- [] JIRA ticket links to this PR: 
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered.
    * In rare situations, this may not be possible or applicable to a PR. In those situations:
        1. Note why this could not be done or is not applicable here:
        2. Add TODOs in the code noting that it requires a test
        3. Add a JIRA task to add the test and link it here:
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint: N/A

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-03-21 19:55 UTC, lukoktonos requested changes

2018-03-21 19:55 UTC, losborne commented on test/unit/cql_loader_test.rb
> +      # Confirm that the source data criteria with the direct reference code is equal to the expected hash
This comment doesn't seem to match the following line.

2018-03-21 19:55 UTC, losborne commented on test/unit/cql_loader_test.rb
> +      measure_details = { 'episode_of_care'=> false }
There's a missing space before `=>`

2018-03-22 14:10 UTC, lukoktonos approved these changes
Looks good

2018-03-23 19:13 UTC, mayerm94 approved these changes

2018-03-29 14:05 UTC, edeyoung commented
failing due to security vulnerabilities - need to update to latest prod release

2018-03-29 14:06 UTC, merged