added vs by oid method
MeasureAuthoringTool/bonnie_bundler pull request #154
Opened 2018-07-17 11:59 UTC by daco101

This adds a method to the cql_measure model that returns value sets by oid, used in the backend calculation.

Pull requests into Bonnie Bundler require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered.
    * In rare situations, this may not be possible or applicable to a PR. In those situations:
        1. Note why this could not be done or is not applicable here:
        2. Add TODOs in the code noting that it requires a test
        3. Add a JIRA task to add the test and link it here:
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-07-17 14:39 UTC, lukoktonos requested changes

2018-07-17 14:39 UTC, losborne commented on lib/models/cql_measure.rb
> +          @value_sets_by_oid[vs.oid] = { vs.version => vs }
It looks like the test never hits this line.  I wrote a loop on bonnie to see which measures from `bonnie-fixtures@mitre.org` might hit it, and here's which ones got to that condition:

CMS158v6
CMS160v6
CMS177v6
CMS32v7
CMS146v6
CMS136v7
CMS720v0
CMS759v1
CMS722v0
CMS760v0
CMS52v7
CMS761v0
CMSv9999
CMS529v0
CMS334v1
CMS460v0

Here's the loop if it's useful:
```
    task :all_value_sets_by_oid => :environment do
      bonnie_fixtures_user_id = User.find_by email: 'bonnie-fixtures@mitre.org'
      bonnie_fixture_measures = CqlMeasure.where user_id: bonnie_fixtures_user_id  
      bonnie_fixture_measures.all.each do |measure|
        if measure.value_sets_by_oid
          puts measure.cms_id
        end
      end
```

2018-07-17 16:00 UTC, jbradl11 requested changes
This should be into a different branch. Create a bonnie-v2.3-backend-calculation branch (based off of Bonnie-v2.3) and make a PR into that. We want to leave Bonnie-v2.3 alone until the entire feature is complete.

2018-07-17 16:10 UTC, jbradl11 commented on lib/models/cql_measure.rb
> +  #note, this method could be duplicate onto the measure model as well
You can remove this node. Measure model is no longer used.

2018-07-17 16:11 UTC, jbradl11 commented on lib/models/cql_measure.rb
> +        # the version corresponding to this measure for the fixture.
Looks like this comment needs to be updated.

2018-07-19 20:44 UTC, jbradl11 commented
The comment still needs to be updated (it mentions fixtures).

2018-07-20 14:29 UTC, jbradl11 approved these changes
Change looks good.

2018-07-20 14:38 UTC, lukoktonos approved these changes

2018-07-20 15:13 UTC, merged