Composite measures
MeasureAuthoringTool/bonnie_bundler pull request #167
Opened 2018-10-19 18:52 UTC by hackrm

Pull requests into Bonnie Bundler require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

Updated bonnie_bundler so composite measures can now be loaded.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [ ] JIRA ticket for this PR: 
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Code coverage has not gone down and all code touched or added is covered.
    * In rare situations, this may not be possible or applicable to a PR. In those situations:
        1. Note why this could not be done or is not applicable here:
        2. Add TODOs in the code noting that it requires a test
        3. Add a JIRA task to add the test and link it here:
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-10-22 20:36 UTC, hossenlopp requested changes

2018-10-22 20:36 UTC, hossenlopp commented on lib/models/cql_measure.rb
> +    if self.hqmf_set_id.count("&") > 0
The body of this function could simply be: ```self.hqmf_set_id.count("&") > 0```

2018-10-22 20:36 UTC, hossenlopp commented on lib/models/cql_measure.rb
> +  def is_component
To follow ruby naming guidelines for methods that return boolean, this method name should end with a question mark.

2018-10-22 20:36 UTC, hossenlopp commented on lib/measures/loading/cql_loader.rb
> +    def self.valid_measure_contents?(f_path)
`f_path` should be a bit more descriptive in its naming.

2018-10-22 20:36 UTC, hossenlopp commented on lib/measures/loading/cql_loader.rb
> +    def self.create_measure(measure_dir, user, measure_details, vsac_options, vsac_ticket_granting_ticket, component_elm_files=nil)
Why are the component_elm_files passed in here and used on line 221? It looks like line 213 fetches all files from the directory.

2018-10-22 20:36 UTC, hossenlopp commented on lib/measures/loading/cql_loader.rb
> +      cql_paths = Dir.glob(File.join("#{dir}/**.cql")).select
I think `.select` not needed here since it is intended to take a block to filter the array. In this case no block is given.

Additionally, this could be where a `.sort` could be added to make the ordering of libraries consistent.

2018-10-25 13:14 UTC, hossenlopp commented on lib/measures/loading/cql_loader.rb
> +    def self.create_component_measures(component_measures, current_directory, current_user, measure_details, vsac_options, vsac_ticket_granting_ticket)
This method be encapsulated by creating the list of component_measures in the method and returning the list, instead passing in an empty array to fill.

2018-10-25 17:13 UTC, hossenlopp commented on test/unit/composite_cql_loader_test.rb
> +      assert_raise NoMethodError do
This should be raising a `MeasureLoadingException`.

2018-10-26 17:22 UTC, hossenlopp commented on lib/models/cql_measure.rb
> +  field :components, type: Array, default: []
This field would be more descriptive if named `:component_hqmf_set_ids`.

2018-10-26 17:24 UTC, hossenlopp commented on lib/models/cql_measure.rb
> +  def is_component?
Should be replaced with a field to mark it as a component instead of trusting the existence of the `&`.

2018-10-29 20:18 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +            component_elms[:ELM_XML] = component_measure.elm_annotations.merge(component_elms[:ELM_XML])
@mayerm94 Didn't we decide that `elm_annotations` for component measures would not be stored on the composite measure?

2018-10-29 20:24 UTC, mayerm94 commented on lib/measures/loading/cql_loader.rb
> +            component_elms[:ELM_XML] = component_measure.elm_annotations.merge(component_elms[:ELM_XML])
Yeah, i thought @zlister had a commit that removed this after the discussion about the comment here https://github.com/projecttacoma/bonnie_bundler/pull/167/commits/80f58c99680ce4d1a280fd5e0a0fec9b248613a2#r227127457 I do not see that commit though

2018-10-29 20:25 UTC, mayerm94 commented on lib/measures/loading/cql_loader.rb
> +            component_elms[:ELM_XML] = component_measure.elm_annotations.merge(component_elms[:ELM_XML])
I can't link to the comment for some reason. It says @zlister marked the comment as resolved

2018-10-29 20:32 UTC, zlister commented on lib/measures/loading/cql_loader.rb
> +            component_elms[:ELM_XML] = component_measure.elm_annotations.merge(component_elms[:ELM_XML])
Hmm... I thought I did make that commit. Looking through the logs it doesn't look like I did. Fixing that now.

2018-10-31 15:35 UTC, mayerm94 approved these changes

2018-10-31 17:18 UTC, hossenlopp commented on Gemfile
> +gem 'health-data-standards', :git => 'https://github.com/projectcypress/health-data-standards.git', :branch => 'composite_measures'
Can be updated to `bonnie-v3.1` branch now.

2018-10-31 17:47 UTC, hossenlopp commented on Gemfile
> +gem 'health-data-standards', :git => 'https://github.com/projectcypress/health-data-standards.git', :branch => 'composite_measures'
The Gemfile.lock needs to be updated as well.

2018-10-31 17:58 UTC, hossenlopp commented on test/fixtures/vcr_cassettes/multi_library_webcalls.yml
>        Content-Type:
This cassette should not have been re-recorded.

2018-10-31 18:56 UTC, hossenlopp commented on test/fixtures/vcr_cassettes/multi_library_webcalls.yml
>        Content-Type:
After discussion in the lab we decided to not worry about this.

2018-10-31 20:33 UTC, hossenlopp approved these changes

2018-11-01 12:46 UTC, merged