Multi library support
MeasureAuthoringTool/bonnie_bundler pull request #86
Opened 2017-06-22 16:23 UTC by jbradl11

This pull request is to add multiple library support to bonnie. In order to test this please checkout the Bonnie branch (cql4bonnie_multi_library_local_id). That branch will allow you to view multiple libraries in the measure details page and execute them correctly. Here is a measure that Paul created for testing. 
[bonnienesting01_fixed.zip](https://github.com/projecttacoma/bonnie_bundler/files/1095459/bonnienesting01_fixed.zip)

2017-06-23 12:37 UTC, edeyoung requested changes
Mostly questions but a few change requests too. Looks nice!

2017-06-23 12:37 UTC, edeyoung commented on lib/measures/loading/cql_loader.rb
> +          model.observations.each do |obs|
is there anything that needs to be done with the observations and multiple libraries? Maybe it's not necessary or I missed it.

2017-06-23 12:37 UTC, edeyoung commented on lib/measures/loading/cql_loader.rb
> +    # Parse the JSON response into an array of json objects (one for each library)
awesome comments!

2017-06-23 12:37 UTC, edeyoung commented on lib/measures/loading/cql_loader.rb
> +      # { 'IPP' => ['Initial Population'] }
I feel like I need some context for this comment. Is this `populatiosn_cql_map`? If so, note that in the comment.

2017-06-23 12:37 UTC, edeyoung commented on lib/measures/loading/cql_loader.rb
> +        cql_population_statement_map[population] = retrieve_all_statements_in_population(population_statement, elms)
This looks like the structure we might use for determining what sub-statements shouldn't be colored for logic calc or used in coverage computations

2017-06-23 12:37 UTC, edeyoung commented on lib/measures/loading/cql_loader.rb
> +      # TODO: Check if sub_statement_name is another Population do we remove?
good question! I think for logic display (the tree display that they use in the human readable), no, we don't want to remove. However, if we also use this for coverage calculations, it might be convenient to remove them on a priority basis. Maybe there can be a switch that gets passed in? Or maybe for coverage calculations, this should just be something that gets determined externally.

2017-06-23 12:37 UTC, edeyoung commented on lib/measures/loading/cql_loader.rb
> +    def self.retrieve_expressions_from_statement(h)
i'm not a fan of single letter variables. Look at expanding with better variable names

2017-06-23 12:37 UTC, edeyoung commented on lib/measures/loading/cql_loader.rb
> +            expressions << h['name'] unless h['name'] == 'Patient'
why `unless h['name'] == 'Patient'`?

2017-06-23 12:37 UTC, edeyoung commented on lib/models/cql_measure.rb
> +  field :elm, type: Array
should `cql` and `elm` be renamed to make it more clear that they are arrays?

2017-06-23 12:37 UTC, edeyoung commented on lib/measures/loading/cql_loader.rb
> +        parsed_elm['library']['valueSets']['def'].each do |value_set|
maybe rename to just `elm`? I know that it is "parsed elm"  but that's now hidden in the function and I think including it here makes it a bit confusing.

2017-06-23 12:37 UTC, edeyoung commented on lib/measures/loading/loader.rb
> +      measure.cql_statement_dependencies = cql_definition_dependency_structure
where do these eventually get used? Or do we just know that we will need to use them in the future?

2017-06-23 15:42 UTC, mayerm94 commented on lib/measures/loading/cql_loader.rb
> +            cql_contents << open(cql_path).read
Could a user technically inject code here by setting their .cql file name to something crazy?

2017-06-23 16:38 UTC, c-monkey commented on lib/measures/loading/cql_loader.rb
> +            cql_contents << open(cql_path).read
@hossenlopp has a lot of experience with this.

2017-06-23 16:42 UTC, hossenlopp commented on lib/measures/loading/cql_loader.rb
> +            cql_contents << open(cql_path).read
The Ruby Zip gem should handle the bad filename stuff. I think that cql_path may be a temporary path that is created by the Ruby Zip gem.

2017-06-26 11:51 UTC, mayerm94 commented on lib/measures/loading/cql_loader.rb
> +        parsed_elm['library']['valueSets']['def'].each do |value_set|
"undefined method `[]' for nil:NilClass" at this line when attempting to load this measure that uses libraries.
[qdmresultratio-2_v5_2_Artifacts.zip](https://github.com/projecttacoma/bonnie_bundler/files/1101962/qdmresultratio-2_v5_2_Artifacts.zip)

2017-06-26 18:44 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +        parsed_elm['library']['valueSets']['def'].each do |value_set|
This was an issue because the support library did not contain value sets. I modified the above code to check if value sets exist. Side note, that measure is very good to test with.

2017-06-26 18:45 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +        parsed_elm['library']['valueSets']['def'].each do |value_set|
I agree. Changed the name.

2017-06-26 19:06 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +          model.observations.each do |obs|
I don't believe so. I will need to test once observations are working.

2017-06-26 19:07 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +      # { 'IPP' => ['Initial Population'] }
You would be correct. I'll add a comment.

2017-06-26 20:00 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +        cql_population_statement_map[population] = retrieve_all_statements_in_population(population_statement, elms)
That is what I was going for. We currently do not use this structure.

2017-06-26 20:04 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +      # TODO: Check if sub_statement_name is another Population do we remove?
I will make a note that we do not currently remove "Populations" and I will remove the "TODO".

2017-06-26 20:06 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +    def self.retrieve_expressions_from_statement(h)
Good call. Renamed the variable.

2017-06-26 20:29 UTC, jbradl11 commented on lib/measures/loading/cql_loader.rb
> +            expressions << h['name'] unless h['name'] == 'Patient'
We are ignoring the references to a Patient expression because it is meaningless to track. It isn't an actual define statement in the logic, but rather a reference to the Patient. Ill add a comment.

2017-06-26 20:32 UTC, jbradl11 commented on lib/measures/loading/loader.rb
> +      measure.cql_statement_dependencies = cql_definition_dependency_structure
We currently do not use cql_statement_dependencies. I thought something like that will be useful for a handful of reasons in the future. We currently use main_cql_library for multi library support, telling the execution engine which library is the measure.

2017-06-26 20:44 UTC, jbradl11 commented on lib/models/cql_measure.rb
> +  field :elm, type: Array
I am open to naming it "elms" and "cqls" or "elm_array" and "cql_array". Thoughts?

2017-06-27 16:18 UTC, holmesie approved these changes

2017-06-27 16:18 UTC, holmesie commented
Looks good

2017-06-27 16:42 UTC, edeyoung commented on lib/measures/loading/cql_loader.rb
> +            # We ignore the Patient expression because it isn't an actual define statment in the cql
Do we also need to do something with the "Population" expression? Or am I thinking of the wrong thing? Is this "context Patient" "context Population" or something else?

2017-06-27 16:44 UTC, edeyoung commented on lib/models/cql_measure.rb
> +  field :elm, type: Array
i'm good with either, but I read a thing once that was like, "adding an 's' doesn't sufficiently differentiate the name from the singular." I personally like just adding "s"es.

2017-06-27 16:52 UTC, mayerm94 approved these changes
Tested Locally.

2017-06-27 17:03 UTC, edeyoung requested changes
"elm"/"cql" need to get pluralized.

I don't seem to be able to test this. I keep seeing the "Outdated Measure!" warning.

2017-06-27 17:04 UTC, jbradl11 commented on lib/models/cql_measure.rb
> +  field :elm, type: Array
I am going to add "s". I believe this will make us have to change Bonnie code where we check to make sure the measure has "cql" in it.

2017-06-27 17:08 UTC, hossenlopp commented
@edeyoung That would make sense because changes are needed in the logic view in bonnie to handle the elm field getting changed to be an Array of elm structures.

2017-06-27 17:29 UTC, edeyoung approved these changes

2017-06-27 17:30 UTC, edeyoung commented
approved pending plural change

2017-06-27 17:36 UTC, hossenlopp approved these changes

2017-06-27 20:19 UTC, c-monkey approved these changes
tested locally

2017-06-27 20:19 UTC, merged