Added logic to further support observations in HQMF+CQL
MeasureAuthoringTool/bonnie_bundler pull request #87
Opened 2017-06-27 22:12 UTC by holmesie

This is the second of three pull requests, the other two are:
https://github.com/projectcypress/health-data-standards/pull/506

2017-06-27 22:47 UTC, mulcahyk commented on lib/models/cql_measure.rb
> +  end
This method made me do a double take.  The `true` by itself was confusing at first.  Perhaps a comment that the `before_save` action needs to have a return of *true* or something.

For consistency I think that `continous_variable` should have a default value of false.  That way it is explicit.

2017-06-27 23:57 UTC, holmesie commented on lib/models/cql_measure.rb
> +  end
Great question!

The return value of this function is not related to whether or not this measure is a CV measure. The `true` return value is related to how `before_save` declarations are handled in Rails. If you were to return false here (which could happen if line 96 was `false`), the chain of `before_save` executions would be halted (see http://devdocs.io/rails~4.2/activerecord/callbacks) - which would obviously break the creation of an instance of this model. (also, FYI, this behavior has been changed since Rails 5).

The line that sets `self.continuous_variable` will always be true if this measure is CV, and will always be false if it is not, so I don't think there is any need to worry about a default value.

Note that this exact function was taken verbatim from the older model.

2017-06-28 17:22 UTC, edeyoung commented on lib/models/cql_measure.rb
> +  end
I think because we have varying levels of ruby expertise, it makes sense to comment things like this.

2017-06-28 18:58 UTC, holmesie commented on lib/models/cql_measure.rb
> +  end
Done!

2017-06-28 20:10 UTC, edeyoung commented on lib/measures/loading/cql_loader.rb
> +        repl_name = '_' + repl_name while cql.include?(repl_name) && func_name[1..-2] != repl_name
why the change for func_name? What characters are you removing here? and why did it work previously (or did it)?

2017-06-28 20:13 UTC, edeyoung requested changes

2017-06-28 20:13 UTC, edeyoung commented on lib/models/cql_measure.rb
> +    self.continuous_variable = populations.map {|x| x.keys}.flatten.uniq.include? HQMF::PopulationCriteria::MSRPOPL
this is a boolean, yes? should this be renamed to "is_continuous_variable" or "continous_variable?"?

Also, maybe add a comment to the function:
"Note whether or not the measure is a continuous variable measure."

2017-06-29 14:16 UTC, holmesie commented on lib/measures/loading/cql_loader.rb
> +        repl_name = '_' + repl_name while cql.include?(repl_name) && func_name[1..-2] != repl_name
This was an oversight originally; the change ignores the quotes that exist in func_name when comparing to repl_name, which does not contain quotes.

2017-06-29 14:18 UTC, holmesie commented on lib/models/cql_measure.rb
> +    self.continuous_variable = populations.map {|x| x.keys}.flatten.uniq.include? HQMF::PopulationCriteria::MSRPOPL
This variable reflects the original QDM based measure model; which means `continuous_variable` is referenced all over the place in Bonnie - so we probably shouldn't deviate.

I'll add the comment you mentioned.

2017-06-30 14:37 UTC, edeyoung approved these changes

2017-06-30 14:38 UTC, mayerm94 approved these changes
Tested locally with CMS55

2017-06-30 15:00 UTC, mulcahyk approved these changes
The comment on the before_save addresses my concern perfectly.

2017-07-10 16:42 UTC, merged