For Code Review - Multi Library Clause Annotations with Statement Dependencies
MeasureAuthoringTool/bonnie_bundler pull request #89
Opened 2017-07-11 15:44 UTC by hossenlopp

This PR is for code review. To be completed with Bonnie PR to be created later.

If you wish to run this branch use the [cql4bonnie_706_707_clause_logic](https://github.com/projecttacoma/bonnie/tree/cql4bonnie_706_707_clause_logic) bonnie branch. With the 1.2.6 translation server and cql4browsers with multi-library support.

Check my 7/9 mailing list email titled "CQL Clause Level Highlighting, Coverage and Multi Library Merged" for more details on how to run and where to get the jar and cql4browsers.js.

2017-07-11 16:48 UTC, jbradl11 commented on lib/measures/elm_parser.rb
> +  class Parser
This class and the functions in the class all need comments. It is difficult to follow along with what is happening with no context.

2017-07-11 16:49 UTC, jbradl11 commented on lib/measures/elm_parser.rb
> +#      ret = Nokogiri::HTML.fragment('<div id="statements"></div>')
Will we need this line eventually? If so, please specify why and when, otherwise remove it.

2017-07-11 16:50 UTC, jbradl11 commented on lib/measures/elm_parser.rb
> +                #text: child.to_html.gsub("\n", '<br/>').gsub(/\s/, "&#160;")
Similarly to my above comment.

2017-07-11 17:20 UTC, alexanderelliott121 commented on lib/measures/elm_parser.rb
> +  class Parser
Comments added.

2017-07-14 01:05 UTC, ssayer requested changes

2017-07-14 01:05 UTC, ssayer commented on lib/measures/elm_parser.rb
> +      parent_type = parent_type.downcase unless parent_type.nil?
Does this line do anything? I don't see parent_type actually being used anywhere. Is this suppose to change the value that's passed in? If so  it should be something like

parent_type.downcase! if parent_type

2017-07-14 01:05 UTC, ssayer commented on lib/measures/elm_parser.rb
> +        rescue Exception => e
There are very few cases where you should rescue from Exception in Ruby. Unless you have a good reason you should rescue from StandardError instead.

2017-07-14 01:05 UTC, ssayer commented on lib/measures/elm_parser.rb
> +      return ret, define_name
You don't need return here because it's at the end of the function, so it's automatically returned

(this is just my personal preference)

2017-07-14 01:05 UTC, ssayer commented on lib/measures/elm_parser.rb
> +    def self.parse_node(node, parent_type=nil)
This method is really long and complex, can it be broken up a little bit?

2017-07-14 01:06 UTC, ssayer commented on lib/measures/elm_parser.rb
> +module CQL_ELM
Is there a reason the module is the standard Ruby CamelCase

2017-07-14 01:07 UTC, ssayer commented on lib/measures/elm_parser.rb
> +        rescue Exception => e
Or if you don't actually care about the "puts e" line, you can just say "rescue"

2017-07-14 12:23 UTC, alexanderelliott121 commented on lib/measures/elm_parser.rb
> +      parent_type = parent_type.downcase unless parent_type.nil?
parent_type is an artifact of a previous version of the cql-to-elm translator.  Removed.

2017-07-14 12:29 UTC, alexanderelliott121 commented on lib/measures/elm_parser.rb
> +    def self.parse_node(node, parent_type=nil)
I'm hesitant to break it up.  There is only a single "if", and the different scenarios in that if are not particularly reusable.  I don't think it would add much clarity to break it up into functions.

2017-07-14 15:21 UTC, alexanderelliott121 commented on lib/measures/elm_parser.rb
> +      return ret, define_name
Removing it breaks things.  I personally dislike the naked returns in Ruby.

2017-07-14 15:22 UTC, alexanderelliott121 commented on lib/measures/elm_parser.rb
> +module CQL_ELM
Changed to CamelCase

2017-07-14 16:06 UTC, ssayer approved these changes

2017-07-14 16:24 UTC, c-monkey commented on lib/measures/elm_parser.rb
> +      #TODO: This is ugly, hopefully the stuff we get from the translation service will give good data
The MAT 5.4 is likely to have integrated Bryn's new "pretty-printing" support for the CQL. If so, we are likely going to need to format our whitespace to match the CQL we receive from the MAT.

I think we should update this comment to incorporate this likely change - although we are pending a 7/18 CQL Testing planning meeting to make a decision if the MAT will include pretty printing.

2017-07-14 16:58 UTC, c-monkey approved these changes

2017-07-18 01:50 UTC, merged